import { MigrationInterface, QueryRunner } from "typeorm";

export class AlterTablesUser1695768600552 implements MigrationInterface {
    name = 'AlterTablesUser1695768600552'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_ngo" ("id" varchar PRIMARY KEY NOT NULL, "cnpj" varchar(14) NOT NULL, "name_ngo" varchar(45) NOT NULL, "date_register" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_32edca82504143adb7a8bda1c3" UNIQUE ("user"), CONSTRAINT "REL_e7225cd89f80ae8237a312726e" UNIQUE ("user_id"), CONSTRAINT "UQ_9182da7b6904c65042d60ead3f4" UNIQUE ("name_ngo"), CONSTRAINT "UQ_3a730f37d3013bf3f184a20111e" UNIQUE ("cnpj"), CONSTRAINT "FK_32edca82504143adb7a8bda1c37" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e7225cd89f80ae8237a312726e9" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ngo"("id", "cnpj", "name_ngo", "date_register", "user_id", "user") SELECT "id", "cnpj", "name_ngo", "date_register", "user_id", "user" FROM "ngo"`);
        await queryRunner.query(`DROP TABLE "ngo"`);
        await queryRunner.query(`ALTER TABLE "temporary_ngo" RENAME TO "ngo"`);
        await queryRunner.query(`CREATE TABLE "temporary_person" ("id" varchar PRIMARY KEY NOT NULL, "cpf" varchar(11) NOT NULL, "date_birth" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_e08f75ffbab3620fc9746ee878" UNIQUE ("user"), CONSTRAINT "REL_5157fa65538cae06e66c922c89" UNIQUE ("user_id"), CONSTRAINT "UQ_264b7cad2330569e0ef5b4c39c4" UNIQUE ("cpf"), CONSTRAINT "FK_e08f75ffbab3620fc9746ee8789" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5157fa65538cae06e66c922c898" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_person"("id", "cpf", "date_birth", "user_id", "user") SELECT "id", "cpf", "date_birth", "user_id", "user" FROM "person"`);
        await queryRunner.query(`DROP TABLE "person"`);
        await queryRunner.query(`ALTER TABLE "temporary_person" RENAME TO "person"`);
        await queryRunner.query(`CREATE TABLE "temporary_ngo" ("id" varchar PRIMARY KEY NOT NULL, "cnpj" varchar(14) NOT NULL, "name_ngo" varchar(45) NOT NULL, "date_register" varchar NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_32edca82504143adb7a8bda1c3" UNIQUE ("user"), CONSTRAINT "REL_e7225cd89f80ae8237a312726e" UNIQUE ("user_id"), CONSTRAINT "UQ_9182da7b6904c65042d60ead3f4" UNIQUE ("name_ngo"), CONSTRAINT "UQ_3a730f37d3013bf3f184a20111e" UNIQUE ("cnpj"), CONSTRAINT "FK_32edca82504143adb7a8bda1c37" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e7225cd89f80ae8237a312726e9" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ngo"("id", "cnpj", "name_ngo", "date_register", "user_id", "user") SELECT "id", "cnpj", "name_ngo", "date_register", "user_id", "user" FROM "ngo"`);
        await queryRunner.query(`DROP TABLE "ngo"`);
        await queryRunner.query(`ALTER TABLE "temporary_ngo" RENAME TO "ngo"`);
        await queryRunner.query(`CREATE TABLE "temporary_person" ("id" varchar PRIMARY KEY NOT NULL, "cpf" varchar(11) NOT NULL, "date_birth" varchar NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_e08f75ffbab3620fc9746ee878" UNIQUE ("user"), CONSTRAINT "REL_5157fa65538cae06e66c922c89" UNIQUE ("user_id"), CONSTRAINT "UQ_264b7cad2330569e0ef5b4c39c4" UNIQUE ("cpf"), CONSTRAINT "FK_e08f75ffbab3620fc9746ee8789" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5157fa65538cae06e66c922c898" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_person"("id", "cpf", "date_birth", "user_id", "user") SELECT "id", "cpf", "date_birth", "user_id", "user" FROM "person"`);
        await queryRunner.query(`DROP TABLE "person"`);
        await queryRunner.query(`ALTER TABLE "temporary_person" RENAME TO "person"`);
        await queryRunner.query(`CREATE TABLE "temporary_shelter" ("id" varchar PRIMARY KEY NOT NULL, "responsible_cpf" varchar(11) NOT NULL, "responsible_date_birth" varchar NOT NULL, "name_shelter" varchar NOT NULL, "star_date_shelter" varchar NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_4174333359fe477e96b2929f1a" UNIQUE ("user"), CONSTRAINT "REL_6b37a09b857e638e3200dcc995" UNIQUE ("user_id"), CONSTRAINT "UQ_ca7499ae2ae41a67e488e8cd18c" UNIQUE ("responsible_cpf"), CONSTRAINT "FK_4174333359fe477e96b2929f1ab" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_6b37a09b857e638e3200dcc995d" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_shelter"("id", "responsible_cpf", "responsible_date_birth", "name_shelter", "star_date_shelter", "user_id", "user") SELECT "id", "responsible_cpf", "responsible_date_birth", "name_shelter", "star_date_shelter", "user_id", "user" FROM "shelter"`);
        await queryRunner.query(`DROP TABLE "shelter"`);
        await queryRunner.query(`ALTER TABLE "temporary_shelter" RENAME TO "shelter"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "shelter" RENAME TO "temporary_shelter"`);
        await queryRunner.query(`CREATE TABLE "shelter" ("id" varchar PRIMARY KEY NOT NULL, "responsible_cpf" varchar(11) NOT NULL, "responsible_date_birth" date NOT NULL, "name_shelter" varchar NOT NULL, "star_date_shelter" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_4174333359fe477e96b2929f1a" UNIQUE ("user"), CONSTRAINT "REL_6b37a09b857e638e3200dcc995" UNIQUE ("user_id"), CONSTRAINT "UQ_ca7499ae2ae41a67e488e8cd18c" UNIQUE ("responsible_cpf"), CONSTRAINT "FK_4174333359fe477e96b2929f1ab" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_6b37a09b857e638e3200dcc995d" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "shelter"("id", "responsible_cpf", "responsible_date_birth", "name_shelter", "star_date_shelter", "user_id", "user") SELECT "id", "responsible_cpf", "responsible_date_birth", "name_shelter", "star_date_shelter", "user_id", "user" FROM "temporary_shelter"`);
        await queryRunner.query(`DROP TABLE "temporary_shelter"`);
        await queryRunner.query(`ALTER TABLE "person" RENAME TO "temporary_person"`);
        await queryRunner.query(`CREATE TABLE "person" ("id" varchar PRIMARY KEY NOT NULL, "cpf" varchar(11) NOT NULL, "date_birth" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_e08f75ffbab3620fc9746ee878" UNIQUE ("user"), CONSTRAINT "REL_5157fa65538cae06e66c922c89" UNIQUE ("user_id"), CONSTRAINT "UQ_264b7cad2330569e0ef5b4c39c4" UNIQUE ("cpf"), CONSTRAINT "FK_e08f75ffbab3620fc9746ee8789" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5157fa65538cae06e66c922c898" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "person"("id", "cpf", "date_birth", "user_id", "user") SELECT "id", "cpf", "date_birth", "user_id", "user" FROM "temporary_person"`);
        await queryRunner.query(`DROP TABLE "temporary_person"`);
        await queryRunner.query(`ALTER TABLE "ngo" RENAME TO "temporary_ngo"`);
        await queryRunner.query(`CREATE TABLE "ngo" ("id" varchar PRIMARY KEY NOT NULL, "cnpj" varchar(14) NOT NULL, "name_ngo" varchar(45) NOT NULL, "date_register" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_32edca82504143adb7a8bda1c3" UNIQUE ("user"), CONSTRAINT "REL_e7225cd89f80ae8237a312726e" UNIQUE ("user_id"), CONSTRAINT "UQ_9182da7b6904c65042d60ead3f4" UNIQUE ("name_ngo"), CONSTRAINT "UQ_3a730f37d3013bf3f184a20111e" UNIQUE ("cnpj"), CONSTRAINT "FK_32edca82504143adb7a8bda1c37" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e7225cd89f80ae8237a312726e9" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ngo"("id", "cnpj", "name_ngo", "date_register", "user_id", "user") SELECT "id", "cnpj", "name_ngo", "date_register", "user_id", "user" FROM "temporary_ngo"`);
        await queryRunner.query(`DROP TABLE "temporary_ngo"`);
        await queryRunner.query(`ALTER TABLE "person" RENAME TO "temporary_person"`);
        await queryRunner.query(`CREATE TABLE "person" ("id" varchar PRIMARY KEY NOT NULL, "cpf" varchar(11) NOT NULL, "date_birth" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_e08f75ffbab3620fc9746ee878" UNIQUE ("user"), CONSTRAINT "REL_5157fa65538cae06e66c922c89" UNIQUE ("user_id"), CONSTRAINT "UQ_264b7cad2330569e0ef5b4c39c4" UNIQUE ("cpf"), CONSTRAINT "FK_e08f75ffbab3620fc9746ee8789" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5157fa65538cae06e66c922c898" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "person"("id", "cpf", "date_birth", "user_id", "user") SELECT "id", "cpf", "date_birth", "user_id", "user" FROM "temporary_person"`);
        await queryRunner.query(`DROP TABLE "temporary_person"`);
        await queryRunner.query(`ALTER TABLE "ngo" RENAME TO "temporary_ngo"`);
        await queryRunner.query(`CREATE TABLE "ngo" ("id" varchar PRIMARY KEY NOT NULL, "cnpj" varchar(14) NOT NULL, "name_ngo" varchar(45) NOT NULL, "date_register" date NOT NULL, "user_id" varchar, "user" varchar, CONSTRAINT "REL_32edca82504143adb7a8bda1c3" UNIQUE ("user"), CONSTRAINT "REL_e7225cd89f80ae8237a312726e" UNIQUE ("user_id"), CONSTRAINT "UQ_9182da7b6904c65042d60ead3f4" UNIQUE ("name_ngo"), CONSTRAINT "UQ_3a730f37d3013bf3f184a20111e" UNIQUE ("cnpj"), CONSTRAINT "FK_32edca82504143adb7a8bda1c37" FOREIGN KEY ("user") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_e7225cd89f80ae8237a312726e9" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ngo"("id", "cnpj", "name_ngo", "date_register", "user_id", "user") SELECT "id", "cnpj", "name_ngo", "date_register", "user_id", "user" FROM "temporary_ngo"`);
        await queryRunner.query(`DROP TABLE "temporary_ngo"`);
    }

}
