GET http://localhost:3000/personality

###
POST http://localhost:3000/personality
Content-Type: application/json

{
    "name": "Bricalhão"
}

###
PUT http://localhost:3000/personality/6e78e4e4-46e7-4fa4-9b7c-eb6e10edc329
Content-Type: application/json

{
    "name": "Bobão"
}

###
DELETE  http://localhost:3000/personality/d6a3a5c7-451d-4b55-980f-1d14c1e3dab0
Content-Type: application/json
