POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sthe@sthe.com",
    "password": "Sthe1234"
}

###
POST http://localhost:3000/auth/reset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGUiLCJlbWFpbCI6InN0aGVAc3RoZS5jb20iLCJpYXQiOjE3MDA1ODE3NTQsImV4cCI6MTcwMTE4NjU1NCwiYXVkIjoidXNlcnMiLCJpc3MiOiJBUEkgQmljaG9zIiwic3ViIjoiN2M0ZGNjMzYtZjVkYi00YmU0LWFmOGMtMTFlMTIxZDAxZGQ5In0.Rmkm26FZF6Z2ojcc6GoUwrWg9gsj_6TeLUcI4F24T7s

{
    "password": "Sthe1234"
}

###
POST http://localhost:3000/auth/forget
Content-Type: application/json

{
    "email": "sthe@sthe.com"
}

###
GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGUiLCJlbWFpbCI6InN0aGVAc3RoZS5jb20iLCJpYXQiOjE3MDAxMDQwMjIsImV4cCI6MTcwMDcwODgyMiwiYXVkIjoidXNlcnMiLCJpc3MiOiJBUEkgQmljaG9zIiwic3ViIjoiMjY2YTE1OTMtN2EzOC00Yjc5LThkNzktM2Y4ZDg0OGUwMzlmIn0.G26UY4hJxQraMlzYTCPoAQLxYvHYSars0LUBckHjgUw