POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sthe1@sthe.com",
    "password": "Sthe1234"
}

###
POST http://localhost:3000/auth/reset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGUiLCJlbWFpbCI6InN0aGVAc3RoZS5jb20iLCJpYXQiOjE3MDA1ODE3NTQsImV4cCI6MTcwMTE4NjU1NCwiYXVkIjoidXNlcnMiLCJpc3MiOiJBUEkgQmljaG9zIiwic3ViIjoiN2M0ZGNjMzYtZjVkYi00YmU0LWFmOGMtMTFlMTIxZDAxZGQ5In0.Rmkm26FZF6Z2ojcc6GoUwrWg9gsj_6TeLUcI4F24T7s

{
    "password": "Sthe1234"
}

###
POST http://localhost:3000/auth/forget
Content-Type: application/json

{
    "email": "sthe@sthe.com"
}

###
GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGUxIiwiZW1haWwiOiJzdGhlMUBzdGhlLmNvbSIsImlhdCI6MTcwMDg1MTYyNywiZXhwIjoxNzAxNDU2NDI3LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiIyYmNkNmNiMy0wN2JjLTQ2MmMtOThiZS1hNzliOGQ5YTlhOTQifQ.LW646Z49lZZT1wrNmGyFBjWrRT31Sm7SeDzIF2ksNX8