GET http://localhost:3000/adopt

###
GET http://localhost:3000/adopt/b311acdf-8b30-4306-a300-e345b63d3b6c

###
POST http://localhost:3000/adopt
Content-Type: application/json

{
    "id_adopter": "266a1593-7a38-4b79-8d79-3f8d848e039f",
    "id_post": "107f1538-aa52-4707-a6e0-2db7a2550e3a",
    "id_quiz": "1eef8c38-785a-402d-9fdf-97c7cea2096a",
    "responses": [
        {
            "id_question": "29173629-a4c9-4295-a903-3531f419cff2",
            "response": "aaaaaaaa"
        },
        {
            "id_question": "b7548269-13c7-4d2a-89f7-0f75332f0950",
            "response": "bbbbbbb"
        }
    ]
}

###
POST http://localhost:3000/adopt/evaluate/responses/b311acdf-8b30-4306-a300-e345b63d3b6c
Content-Type: application/json

{
    "evaluations": [
        {
            "id_response": "f1921ead-0027-495c-8862-70f3bf186a80",
            "evaluation": 1
        },
        {
            "id_response": "dc9f756b-f2c5-4bfc-864a-ebd355b4ff98",
            "evaluation": 2
        }
    ]
}

###
PATCH http://localhost:3000/adopt/choose/adopter/6bb369b7-ae70-4e0e-b75d-13f8ba70dc6a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGVmYW55ayIsImVtYWlsIjoic3RoZUBzdGhlLmNvbSIsImlhdCI6MTcwMTExNzE4OCwiZXhwIjoxNzAxNzIxOTg4LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiI1NDM3ZjhmMS1mY2ZhLTQ1YzktOThkZC1mODcyODkyOTJiZjYifQ.K-CNNDmyQFkEdgZbvGUG4U0Gr7pvh84aQSH3LD9rvCE

###
GET http://localhost:3000/adopt/adopter/409ed03f-4244-4789-948b-46df1563c697

