GET http://localhost:3000/adopt

###
GET http://localhost:3000/adopt/b311acdf-8b30-4306-a300-e345b63d3b6c

###
POST http://localhost:3000/adopt
Content-Type: application/json

{
    "id_adopter": "4ca0b600-3282-4264-8bfc-ef5479d1f386",
    "id_post": "21ef439d-89ba-48fd-addf-84f7bda63d9a",
    "id_quiz": "c4500a51-2172-448a-baaa-c6f0c4efed96",
    "responses": [
        {
            "id_question": "81a6cfb5-3de6-4a96-a842-485105ed56e9",
            "response": "aaaaaaaa"
        },
        {
            "id_question": "94ff5131-d6a9-4f68-9013-fe5adb11a86c",
            "response": "bbbbbbb"
        },
        {
            "id_question": "a0dbc192-ec01-4d09-9ae3-07ffc62c8916",
            "response": "bbbbbbb"
        },
        {
            "id_question": "c03ec613-25bf-4f6b-aac9-4032f9b7b527",
            "response": "bbbbbbb"
        },
        {
            "id_question": "f5f46e36-5756-4cd7-a0a3-9b77ecf03acc",
            "response": "bbbbbbb"
        }
    ]
}

###
POST http://localhost:3000/adopt/evaluate/responses/b311acdf-8b30-4306-a300-e345b63d3b6c
Content-Type: application/json

{
    "evaluations": [
        {
            "id_response": "f1921ead-0027-495c-8862-70f3bf186a80",
            "evaluation": 1
        },
        {
            "id_response": "dc9f756b-f2c5-4bfc-864a-ebd355b4ff98",
            "evaluation": 2
        }
    ]
}

###
PATCH http://localhost:3000/adopt/choose/adopter/6bb369b7-ae70-4e0e-b75d-13f8ba70dc6a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGVmYW55ayIsImVtYWlsIjoic3RoZUBzdGhlLmNvbSIsImlhdCI6MTcwMTExNzE4OCwiZXhwIjoxNzAxNzIxOTg4LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiI1NDM3ZjhmMS1mY2ZhLTQ1YzktOThkZC1mODcyODkyOTJiZjYifQ.K-CNNDmyQFkEdgZbvGUG4U0Gr7pvh84aQSH3LD9rvCE

###
GET http://localhost:3000/adopt/adopter/409ed03f-4244-4789-948b-46df1563c697

