POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sthe@sthe.com",
    "password": "Sthe123"
}

###
POST http://localhost:3000/auth/reset
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGVmYW55IiwiZW1haWwiOiJzdGhlQHN0aGUuY29tIiwiaWF0IjoxNjk4NDQ1MDE1LCJleHAiOjE2OTkwNDk4MTUsImF1ZCI6InVzZXJzIiwiaXNzIjoiQVBJIEJpY2hvcyIsInN1YiI6Ijk5YzE1YzQ5LTcwMGMtNDE0Zi05MzIwLTI4OTkwNjkxNWI5ZiJ9.EKRATAdHjRTDkXwL0lwlIOH96kA52WeePnpZoCVHeoQ
Content-Type: application/json

{
    "password": "Sthe1234"
}

###
POST http://localhost:3000/auth/forget
Content-Type: application/json

{
    "email": "sthe@sthe.com"
}

###
GET http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGVmYW55IiwiZW1haWwiOiJzdGhlQHN0aGUuY29tIiwiaWF0IjoxNjk4NDQ3MzAzLCJleHAiOjE2OTkwNTIxMDMsImF1ZCI6InVzZXJzIiwiaXNzIjoiQVBJIEJpY2hvcyIsInN1YiI6Ijk5YzE1YzQ5LTcwMGMtNDE0Zi05MzIwLTI4OTkwNjkxNWI5ZiJ9.WjeMY4c5eVP354ylUf4P4_KGpjeMjQ_XDENPYFG5SsE