POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hash@hash.com",
    "password": "Hash1234"
}

###
POST http://localhost:3000/auth/reset
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGVyc29uIiwiZW1haWwiOiJwZXJzb25AcGVyc29uLmNvbSIsImlhdCI6MTY5NTAxOTEwMywiZXhwIjoxNjk1NjIzOTAzLCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiIyZWZmZDBkNy1kYjIyLTRjNWYtYTk4Yi01NWM1MTA4YmUzYmUifQ.MSxxKgLLlTxNZa47JLXJzIs1EbsaI3YU6jH7EvXuKIw",
    "password": "PasswordReset12345"
}

###
POST http://localhost:3000/auth/forget
Content-Type: application/json

{
    "email": "email@example.com"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "register",
    "email": "register@example.com",
    "password": "Password1"
}

###
POST http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCBoYXNoIiwiZW1haWwiOiJoYXNoQGhhc2guY29tIiwiaWF0IjoxNjk1MDIxNDgwLCJleHAiOjE2OTU2MjYyODAsImF1ZCI6InVzZXJzIiwiaXNzIjoiQVBJIEJpY2hvcyIsInN1YiI6Ijc2ZjY3YzVlLTU0NDQtNGUwMy04MjE2LTYxZDc0MDdjZTYyNiJ9.Fu_AjzuC7cPIny4q8lYp5hIjy908RDgN1a36kluR1Ko