GET http://localhost:3000/breed

###
GET http://localhost:3000/breed/active

###
GET http://localhost:3000/breed/inactive

###
GET http://localhost:3000/breed/specie/1

###
GET http://localhost:3000/breed?filter=ca

###
GET http://localhost:3000/breed?sort=name&sort_dir=asc

###
GET http://localhost:3000/breed?sort=name&sort_dir=desc&filter=p

###
GET http://localhost:3000/breed?page=1&per_page=2

###
GET http://localhost:3000/breed/aa2c1c61-67ad-4443-8405-c6f46d7f12bd

###
POST http://localhost:3000/breed
Content-Type: application/json

{
    "name": "srd",
    "specie": "1"
}

###
PATCH http://localhost:3000/breed/c84c203f-0d0b-48f7-bf6b-02f4ab4121f3
Content-Type: application/json

{
    "name": "srd",
    "specie": "1"
}

###
PATCH http://localhost:3000/breed/activate/a5d11808-90c8-4fa1-bed5-3a34fe295269

###
PATCH http://localhost:3000/breed/inactivate/a5d11808-90c8-4fa1-bed5-3a34fe295269