GET http://localhost:3000/localization/state/Paran%C3%A1

###
GET http://localhost:3000/localization/city/Paran%C3%A1

###
GET http://localhost:3000/localization/states

###
GET http://localhost:3000/localization/cities

###
POST http://localhost:3000/localization/state
Content-Type: application/json

{
    "name": "Paraná",
    "abbreviation": "pr"
}

###
POST http://localhost:3000/localization/city
Content-Type: application/json

{
    "name": "paranaguá",
    "state": "Paraná"
}

###
DELETE  http://localhost:3000/localization/city/Paranaguá
Content-Type: application/json

###
DELETE  http://localhost:3000/localization/state/Paraná

###
GET http://localhost:3000/localization/encode/Paraná
