GET http://localhost:3000/personality

###
GET http://localhost:3000/personality?filter=up

###
POST http://localhost:3000/personality
Content-Type: application/json

{
    "name": "name",
    "email": "email",
    "password": "password"
}

###
PUT  http://localhost:3000/personality/4b430630-b528-4953-8e32-bbe606fc02c1
Content-Type: application/json

{
    "name": "name update",
    "email": "email",
    "password": "password"
}

###
DELETE  http://localhost:3000/personality/c70c8140-dedd-45ef-84ad-126c7214aeb7
Content-Type: application/json
