GET http://localhost:3000/person

###
GET http://localhost:3000/person/active
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGUiLCJlbWFpbCI6InN0aGVAc3RoZS5jb20iLCJpYXQiOjE2OTU2MDIwNzUsImV4cCI6MTY5NjIwNjg3NSwiYXVkIjoidXNlcnMiLCJpc3MiOiJBUEkgQmljaG9zIiwic3ViIjoiYWZmNjZhYjMtMDdkNC00YjYzLTkzNDYtMzgyNThjN2RhOTAzIn0.MaJqr5zNxJtwJDXJyrX-2LUdz75Zh8_H7WwsFAfcYaE

###
GET http://localhost:3000/person/inactive
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0aGUiLCJlbWFpbCI6InN0aGVAc3RoZS5jb20iLCJpYXQiOjE2OTU2MDIwNzUsImV4cCI6MTY5NjIwNjg3NSwiYXVkIjoidXNlcnMiLCJpc3MiOiJBUEkgQmljaG9zIiwic3ViIjoiYWZmNjZhYjMtMDdkNC00YjYzLTkzNDYtMzgyNThjN2RhOTAzIn0.MaJqr5zNxJtwJDXJyrX-2LUdz75Zh8_H7WwsFAfcYaE

###
GET http://localhost:3000/person?filter=2

###
GET http://localhost:3000/person?sort=full_name&sort_dir=asc

###
GET http://localhost:3000/person?sort=full_name&sort_dir=asc&filter=5

###
GET http://localhost:3000/person?page=3&per_page=3

###
GET http://localhost:3000/person/9c0be5d4-a47c-427c-8234-54c45e482448

###
POST http://localhost:3000/person
Content-Type: application/json

{
    "cpf": "00000000009",
    "date_birth": "2002-02-11",
    "full_name": "sthe",
    "username": "sthefany9",
    "email": "sthe9@sthe.com",
    "password": "Sthe1234",
    "city": "Paranaguá",
    "description": "bbbbb",
    "profile_picture": "bbbbb",
    "header_picture": "bbbb"
}


###
PUT   http://localhost:3000/person/8126f7de-fccf-4fa1-978f-115967e4a2cc
Content-Type: application/json

{
    "cpf": "00000000007",
    "date_birth": "2002-02-11",
    "full_name": "hash",
    "username": "hash",
    "email": "hash@hash.com",
    "password": "Hash1234",
    "city": "Paranaguá",
    "description": "aaaaaaa",
    "profile_picture": "aaaaaaa",
    "header_picture": "aaaaaa"
}

###
PATCH http://localhost:3000/person/inactivate/7b63310b-2905-41b7-a0d7-8216fb95d68d
Content-Type: application/json

###
PATCH http://localhost:3000/person/activate/7b63310b-2905-41b7-a0d7-8216fb95d68d
Content-Type: application/json
