GET http://localhost:3000/personality

###
GET http://localhost:3000/personality?filter=up

###
POST http://localhost:3000/personality
Content-Type: application/json

{
    "name": "name",
    "email": "email",
    "password": "password"
}

###
PUT  http://localhost:3000/personality/903ac5ec-c360-4f38-b12d-ac565a26d99c
Content-Type: application/json

{
    "name": "name update",
    "email": "email",
    "password": "password"
}

###
DELETE  http://localhost:3000/personality/903ac5ec-c360-4f38-b12d-ac565a26d99c
Content-Type: application/json
