GET http://localhost:3000/personality

###
GET http://localhost:3000/personality/active

###
GET http://localhost:3000/personality/inactive

###
GET http://localhost:3000/personality?filter=ca

###
GET http://localhost:3000/personality?sort=name&sort_dir=asc

###
GET http://localhost:3000/personality?sort=name&sort_dir=desc&filter=b

###
GET http://localhost:3000/personality?page=1&per_page=2

###
GET http://localhost:3000/personality/ee09e9e0-204c-4f9e-bbe8-5fc7968929ed

###
POST http://localhost:3000/personality
Content-Type: application/json

{
    "name": "calmo"
}

###
PATCH http://localhost:3000/personality/ee09e9e0-204c-4f9e-bbe8-5fc7968929ed
Content-Type: application/json

{
    "name": "bricalhão"
}

###
PATCH http://localhost:3000/personality/activate/ee09e9e0-204c-4f9e-bbe8-5fc7968929ed

###
PATCH http://localhost:3000/personality/inactivate/ee09e9e0-204c-4f9e-bbe8-5fc7968929ed