GET http://localhost:3000/person

###
GET http://localhost:3000/person/active

###
GET http://localhost:3000/person/inactive

###
GET http://localhost:3000/person?filter=2

###
GET http://localhost:3000/person?sort=full_name&sort_dir=asc

###
GET http://localhost:3000/person?sort=full_name&sort_dir=asc&filter=5

###
GET http://localhost:3000/person?page=3&per_page=3

###
GET http://localhost:3000/person/7b63310b-2905-41b7-a0d7-8216fb95d68d

###
POST http://localhost:3000/person
Content-Type: application/json

{
    "cpf": "00000000055",
    "date_birth": "2002-02-11",
    "full_name": "sthe55",
    "username": "sthe55",
    "email": "sthe55@admin.com",
    "password": "AdminUp123",
    "city": "Paranaguá",
    "description": ""
}


###
PUT   http://localhost:3000/person/7b63310b-2905-41b7-a0d7-8216fb95d68d
Content-Type: application/json

{
    "cpf": "00000000003",
    "date_birth": "2002-02-11",
    "full_name": "sthe3",
    "username": "sthe3",
    "email": "udated3@admin.com",
    "password": "AdminUp123",
    "city": "Paranaguá",
    "description": ""
}

###
PATCH http://localhost:3000/person/inactivate/7b63310b-2905-41b7-a0d7-8216fb95d68d
Content-Type: application/json

###
PATCH http://localhost:3000/person/activate/7b63310b-2905-41b7-a0d7-8216fb95d68d
Content-Type: application/json
