GET http://localhost:3000/quiz/242e3501-ad44-49d0-af32-c536e5e796d7

###
POST http://localhost:3000/quiz
Content-Type: application/json

{
    "title": "titulo",
    "description": "description quiz"
}

###
POST http://localhost:3000/quiz/add/question
Content-Type: application/json

{
    "id_quiz": "242e3501-ad44-49d0-af32-c536e5e796d7",
    "question": {
        "question": "Por que bla bla bla?",
        "type": 1,
        "others": false,
        "alternatives": [
            "bla1",
            "bla2"
        ]
    }
}

###
DELETE http://localhost:3000/quiz/question/495fcfd1-6a47-4c20-9a07-29a0c90b5a3a