GET http://localhost:3000/shelter

###
GET http://localhost:3000/shelter/active

###
GET http://localhost:3000/shelter/inactive

###
GET http://localhost:3000/shelter?filter=s

###
GET http://localhost:3000/shelter?sort=full_name&sort_dir=asc

###
GET http://localhost:3000/shelter?sort=full_name&sort_dir=asc&filter=5

###
GET http://localhost:3000/shelter?page=1&per_page=3

###
GET http://localhost:3000/shelter/a6415b19-8611-41b0-93cb-d47245ae88a5

###
POST http://localhost:3000/shelter
Content-Type: application/json

{
    "responsible_cpf": "00000000001",
    "responsible_date_birth": "2002-02-11",
    "name_shelter": "sthe1",
    "star_date_shelter": "2002-02-11",
    "full_name": "sthe1",
    "username": "sthe1",
    "name": "sthe1",
    "email": "sthe1@admin.com",
    "password": "Sthe1234",
    "city": "Paranaguá",
    "description": "",
    "profile_picture": "",
    "header_picture": ""
}


###
PUT   http://localhost:3000/shelter/a6415b19-8611-41b0-93cb-d47245ae88a5
Content-Type: application/json

{
    "responsible_cpf": "00000000002",
    "responsible_date_birth": "2002-02-11",
    "name_shelter": "ssssss",
    "star_date_shelter": "2002-02-11",
    "full_name": "abrigo",
    "username": "ssssssss",
    "name": "sssssssss",
    "email": "sssss@admin.com",
    "password": "AdminUp123",
    "city": "Paranaguá",
    "description": "bbbb",
    "profile_picture": "bbbb",
    "header_picture": "bbbb"
}

###
PATCH http://localhost:3000/shelter/inactivate/a6415b19-8611-41b0-93cb-d47245ae88a5
Content-Type: application/json

###
PATCH http://localhost:3000/shelter/activate/a6415b19-8611-41b0-93cb-d47245ae88a5
Content-Type: application/json
