GET http://localhost:3000/shelter

###
GET http://localhost:3000/shelter/active

###
GET http://localhost:3000/shelter/inactive

###
GET http://localhost:3000/shelter?filter=s

###
GET http://localhost:3000/shelter?sort=full_name&sort_dir=asc

###
GET http://localhost:3000/shelter?sort=full_name&sort_dir=asc&filter=5

###
GET http://localhost:3000/shelter?page=1&per_page=3

###
GET http://localhost:3000/shelter/9c0be5d4-a47c-427c-8234-54c45e482448

###
POST http://localhost:3000/shelter
Content-Type: application/json

{
    "responsible_cpf": "00000000050",
    "responsible_date_birth": "2002-02-11",
    "name_shelter": "sthe950",
    "star_date_shelter": "2002-02-11",
    "full_name": "sthe50",
    "username": "sthe950",
    "email": "sthe50@admin.com",
    "password": "AdminUp123",
    "city": "Paranaguá",
    "description": "ccccc",
    "profile_picture": "ccccc",
    "header_picture": "ccccc"
}


###
PUT   http://localhost:3000/shelter/63bba682-8200-4990-88d3-744f967282bf
Content-Type: application/json

{
    "responsible_cpf": "00000000009",
    "responsible_date_birth": "2002-02-11",
    "name_shelter": "ssssss",
    "star_date_shelter": "2002-02-11",
    "full_name": "abrigo",
    "username": "ssssssss",
    "email": "sssss@admin.com",
    "password": "AdminUp123",
    "city": "Paranaguá",
    "description": "bbbb",
    "profile_picture": "bbbb",
    "header_picture": "bbbb"
}

###
PATCH http://localhost:3000/shelter/inactivate/e2c82320-2ad8-464f-abe3-596c1f3a8f2b
Content-Type: application/json

###
PATCH http://localhost:3000/shelter/activate/e2c82320-2ad8-464f-abe3-596c1f3a8f2b
Content-Type: application/json
