GET http://localhost:3000/sponsorship

###
GET http://localhost:3000/sponsorship/2d94c6c0-87ea-4452-a24e-04e564ec879c

###
POST http://localhost:3000/sponsorship
Content-Type: application/json

{
    "id_godfather": "23c76141-b764-4255-8b5f-cf615525c0ba",
    "id_post": "93632074-8ec9-4bff-bba8-8f0bb8ebf6d0"
}

