GET http://localhost:3000/users

###
GET http://localhost:3000/users?filter=fe

###
GET http://localhost:3000/users?sort=name&sort_dir=asc

###
GET http://localhost:3000/users?sort=name&sort_dir=asc&filter=ja

###
GET http://localhost:3000/users?page=1&per_page=1

###
GET http://localhost:3000/users/60ee032c-06a1-4972-8e04-23075b8a9413

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "aaaaa",
    "email": "email@example.com",
    "password": "Password2"
}

###
PUT   http://localhost:3000/users/60ee032c-06a1-4972-8e04-23075b8a9413
Content-Type: application/json

{
    "name": "henrique",
    "email": "henrique@gmail.com",
    "password": "Henrique1"
}

###
DELETE  http://localhost:3000/users/4b6636a1-62e9-43da-ba9c-4099f966d4cb
Content-Type: application/json
