GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NTAwMjg1NSwiZXhwIjoxNjk1NjA3NjU1LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiIxMTRlNDY3Yi01YmJkLTRmOWUtODgxYS0xNjA1MjFlNDdhNjEifQ.J0QnfX7HrsHk3Lyu_327AJVzm5tbCXX_TgrfZA7cnv8

###
GET http://localhost:3000/users/active

###
GET http://localhost:3000/users?filter=fe

###
GET http://localhost:3000/users?sort=name&sort_dir=asc

###
GET http://localhost:3000/users?sort=name&sort_dir=desc&filter=a

###
GET http://localhost:3000/users?page=1&per_page=5

###
GET http://localhost:3000/user/b00d483e-1cae-469d-acfb-204dc3e310c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NTAwMjg1NSwiZXhwIjoxNjk1NjA3NjU1LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiIxMTRlNDY3Yi01YmJkLTRmOWUtODgxYS0xNjA1MjFlNDdhNjEifQ.J0QnfX7HrsHk3Lyu_327AJVzm5tbCXX_TgrfZA7cnv8

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin2@admin.com",
    "password": "Admin123",
    "role": 0
}

###
PUT   http://localhost:3000/users/3667909d-cf6c-412f-a6f6-bbae1814a38c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NTAwMjg1NSwiZXhwIjoxNjk1NjA3NjU1LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiIxMTRlNDY3Yi01YmJkLTRmOWUtODgxYS0xNjA1MjFlNDdhNjEifQ.J0QnfX7HrsHk3Lyu_327AJVzm5tbCXX_TgrfZA7cnv8

{
    "name": "admin",
    "email": "admin2@admin.com",
    "password": "Admin123",
    "role": 0
}

###
DELETE  http://localhost:3000/users/3667909d-cf6c-412f-a6f6-bbae1814a38c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NTAwMjg1NSwiZXhwIjoxNjk1NjA3NjU1LCJhdWQiOiJ1c2VycyIsImlzcyI6IkFQSSBCaWNob3MiLCJzdWIiOiIxMTRlNDY3Yi01YmJkLTRmOWUtODgxYS0xNjA1MjFlNDdhNjEifQ.J0QnfX7HrsHk3Lyu_327AJVzm5tbCXX_TgrfZA7cnv8

