export enum StatusAdopt {
  WAITING_QUIZ_CLOSE = 0,
  WAITING_EVALUATION = 1,
  CLOSED_BY_TIME = 2,
  REFUSED = 3,
  ACCEPTED = 4,
  CLOSED_BY_POSTER = 5,
  CLOSED_BY_ADOPTER = 6,
  PROCESS_COMPLETED = 7,
}
