export enum StatusPost {
    WAITING_QUESTIONNAIRES = 0,
    WAITING_EVALUATION = 1,
    WAITING_RENEWAL = 2,
    IN_EVALUATION = 3,
    TIME_CLOSURE = 4,
    CLOSED_BY_POSTER = 5,
    PROCESS_COMPLETED = 6
}